### PR TITLE
[wip] image for 2.4.0

### PR DESCRIPTION
**Pull request by Jiri-Kremser**
generated files shouldn't be in the repository.. it's really pain to change anything w/o knowing how and from what are the files generated

### CODE REVIEW

**Comment by elmiko** [comment]
hey Jirka, i'm looking into this to see how we can get 2.4 included in the repo. what do you recommend with regards to this pull request if i want to test it and see what needs to be done?

i was thinking about trying to build what you have here, but i'm curious where you left the _"wip"_ and if i can lend a hand?

**Comment by Jiri-Kremser** [comment]
I think, I was just using git grep for "2.3" and "md5" and replacing it with 2.4 and "sha512". But the same files were like 3 times in the repo... I was clearly editing the generated files, which I couldn't distinguish from the "real" files that should be in the repo :) so I gave up. I wish it would be easier to bump the spark version or to tell which files are generated from the others and contributor shouldn't touch them.

**Comment by elmiko** [comment]
ack, and i agree about how difficult it is to change.

given what you have said, do you mind if i start another pr with an update to 2.4?

**Comment by Jiri-Kremser** [comment]
sure, no problem, I'll close this one. Feel free to (re-)use whatever you want from it.

**Pull request closed without merging**
