### PR TITLE
change spark version to 2.1.0

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by elmiko** [comment]
lgtm

**Comment by tmckayus** [comment]
maybe test.  S2I needs corresponding change for the driver pod, and we should merge them together ...

**Comment by mattf** [comment]
fyi https://github.com/infinispan/infinispan-spark/pull/45

**Comment by willb** [comment]
Gang, is this merge imminent or not?  (If not, I'm going to roll back my notebook images to 2.0.1 in advance of the DevConf workshop.)

**Comment by crobby** [comment]
I think we were going to wait until Monday to do this merge.  Elmiko expressed interest in waiting.

**Comment by willb** [comment]
@crobby ack, thanks

**Comment by elmiko** [comment]
Will, i had asked Trevor to hold off until monday since i based my images on the current openshift-spark. if you want to merge to 2.1.0 i'm ok with that, i just need to rebuild my stuff.

**Comment by zmhassan** [comment]
I'll be replacing the hardcoded url with docker build-args so we can pass in the the url during build time in jenkins.

**Comment by zmhassan** [comment]
When folks want to get say spark version 2.1.0 they do a simple.
```bash
docker pull openshift-spark:v2.1.0
```
Tagged versioning

**Pull request merged**
