### PR TITLE
Convert default image to Python 3.6 and deprecate Python 2.7 images

### PR DESCRIPTION
**Pull request by rimolive**
This is a big refactor commit because cekit upgrade to 3.7.0 forced a lot of code changes

### CODE REVIEW

**Comment by tmckayus** [comment]
After offline discussion, we're going to leave the 2.4.x branch as is with py27 default to maintain backwards compatibility.
Instead, we are going to add a spark 3.0 branch (yay!) and drop py27 for spark 3.0 and above, and move to py3

**Comment by tmckayus** [comment]
@elmiko ^^

**Comment by elmiko** [comment]
that makes sense to me

**Comment by tmckayus** [comment]
The move to Python 3.6 was incorporated into an update to Spark 3.0.0 in https://github.com/radanalyticsio/openshift-spark/pull/111

**Pull request closed without merging**
